### ISSUE TITLE
Project log sink used instead of org level sink

### ISSUE THREAD

**Issue by ocsig** [anners/gcp-pci-terraform#2]
https://github.com/anners/gcp-pci-terraform/blob/8cff3b1ec9a59c9558a76a77d8316f084e2741cc/stackdriver.tf#L46-L52

With this solution logs will be only collected from the Stackdriver project, which is not containing any instances. This should be either an org/folder level sink where child logs are included or more project sinks should be set up. One for each project.

**Comment by anners** [comment]
https://github.com/anners/gcp-pci-terraform/pull/4/commits/2d38f55ef33a5473683aaf567fa988f97e60e0fb

I created and org and project sync (for the in scope project), take a look an let know it if looks better.

**Comment by ocsig** [comment]
Looks good for me
